apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.password }}
