apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: shopnow-priyankp2
type: Opaque
stringData:
  MONGODB_URI: mongodb://shopuser:ShopNowPass123@mongo-0.mongo-headless.shopnow-priyankp2.svc.cluster.local:27017/shopnow?authSource=admin
